# -*- coding: utf-8 -*-
from . import inventory_rule
from . import res_partner
from . import account_payment_group
from . import account_payment
from . import account_invoice
from . import advance_request_type
from . import advance_request
from . import transaction_type
from . import transaction_type_amo_rest
from . import advance_return
from . import expedient_category
from . import location
from . import budget_modification_detail
from . import funding_move
from . import account_invoice_line
from . import rest_type
from . import users
from . import budget_position
from . import company
from . import budget_detail
from . import budget_prec_detail
from . import preventive_line
from . import definitive_line
from . import transaction
from . import budget_position_category
from . import budget
from . import remit
from . import advance_return_line
from . import budget_pos_exc_rest
from . import budget_modification
from . import expedient
from . import advance_request_line
from . import expedient_founder
from . import account_bank_statement
from . import account_journal
from . import account_tax
