{   'active': False,
    'author': u'ADHOC SA',
    'category': u'base.module_category_knowledge_management',
    'data': [   u'security/public_budget_group.xml',
                u'wizard/transaction_definitive_make_invoice_view.xml',
                u'wizard/transaction_create_refund_voucher_view.xml',
                u'wizard/account_payment_add_avance_lines_view.xml',
                u'wizard/public_budget_expedients_move_wizard_view.xml',
                u'view/payment_order_view.xml',
                u'view/inventory_rule_view.xml',
                u'view/voucher_view.xml',
                u'view/invoice_view.xml',
                u'view/advance_request_view.xml',
                u'view/transaction_type_view.xml',
                u'view/transaction_type_amo_rest_view.xml',
                u'view/advance_return_view.xml',
                u'view/expedient_category_view.xml',
                u'view/location_view.xml',
                u'view/budget_modification_detail_view.xml',
                u'view/funding_move_view.xml',
                u'view/invoice_line_view.xml',
                u'view/rest_type_view.xml',
                u'view/budget_position_view.xml',
                u'view/company_view.xml',
                u'view/expedient_move_view.xml',
                u'view/budget_detail_view.xml',
                u'view/budget_prec_detail_view.xml',
                u'view/preventive_line_view.xml',
                u'view/definitive_line_view.xml',
                u'view/account_view.xml',
                u'view/transaction_view.xml',
                u'view/budget_position_category_view.xml',
                u'view/budget_view.xml',
                u'view/advance_return_line_view.xml',
                u'view/budget_pos_exc_rest_view.xml',
                u'view/budget_modification_view.xml',
                u'view/expedient_view.xml',
                u'view/advance_request_line_view.xml',
                u'view/expedient_founder_view.xml',
                u'data/payment_order_properties.xml',
                u'data/inventory_rule_properties.xml',
                u'data/voucher_properties.xml',
                u'data/invoice_properties.xml',
                u'data/advance_request_properties.xml',
                u'data/transaction_type_properties.xml',
                u'data/transaction_type_amo_rest_properties.xml',
                u'data/advance_return_properties.xml',
                u'data/expedient_category_properties.xml',
                u'data/location_properties.xml',
                u'data/budget_modification_detail_properties.xml',
                u'data/funding_move_properties.xml',
                u'data/invoice_line_properties.xml',
                u'data/rest_type_properties.xml',
                u'data/budget_position_properties.xml',
                u'data/company_properties.xml',
                u'data/expedient_move_properties.xml',
                u'data/budget_detail_properties.xml',
                u'data/budget_prec_detail_properties.xml',
                u'data/preventive_line_properties.xml',
                u'data/definitive_line_properties.xml',
                u'data/account_properties.xml',
                u'data/transaction_properties.xml',
                u'data/budget_position_category_properties.xml',
                u'data/budget_properties.xml',
                u'data/advance_return_line_properties.xml',
                u'data/budget_pos_exc_rest_properties.xml',
                u'data/budget_modification_properties.xml',
                u'data/expedient_properties.xml',
                u'data/advance_request_line_properties.xml',
                u'data/expedient_founder_properties.xml',
                u'data/payment_order_track.xml',
                u'data/inventory_rule_track.xml',
                u'data/voucher_track.xml',
                u'data/invoice_track.xml',
                u'data/advance_request_track.xml',
                u'data/transaction_type_track.xml',
                u'data/transaction_type_amo_rest_track.xml',
                u'data/advance_return_track.xml',
                u'data/expedient_category_track.xml',
                u'data/location_track.xml',
                u'data/budget_modification_detail_track.xml',
                u'data/funding_move_track.xml',
                u'data/invoice_line_track.xml',
                u'data/rest_type_track.xml',
                u'data/budget_position_track.xml',
                u'data/company_track.xml',
                u'data/expedient_move_track.xml',
                u'data/budget_detail_track.xml',
                u'data/budget_prec_detail_track.xml',
                u'data/preventive_line_track.xml',
                u'data/definitive_line_track.xml',
                u'data/account_track.xml',
                u'data/transaction_track.xml',
                u'data/budget_position_category_track.xml',
                u'data/budget_track.xml',
                u'data/advance_return_line_track.xml',
                u'data/budget_pos_exc_rest_track.xml',
                u'data/budget_modification_track.xml',
                u'data/expedient_track.xml',
                u'data/advance_request_line_track.xml',
                u'data/expedient_founder_track.xml',
                u'data/sequence.xml',
                u'workflow/transaction_workflow.xml',
                u'workflow/budget_workflow.xml',
                u'workflow/expedient_workflow.xml',
                u'workflow/funding_move_workflow.xml',
                u'workflow/advance_request_workflow.xml',
                u'workflow/advance_return_workflow.xml',
                u'security/ir.model.access.csv',
                u'view/public_budget_menuitem.xml',
                u'wizard/wizards_menus.xml',
                u'view/public_budget_actions.xml'],
    'depends': [u'account', u'account_payment_voucher'],
    'description': u'Public Budget',
    'installable': True,
    'license': 'AGPL-3',
    'name': u'Public Budget',
    'test': [],
    'version': 'No version',
    'website': ''}
# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
