{'active': False,
    'author': 'ADHOC SA',
    'category': 'base.module_category_knowledge_management',
    'data': [
                'security/public_budget_group.xml',
                'view/account_voucher_view.xml',
                'wizard/transaction_definitive_make_invoice_view.xml',
                'view/inventory_rule_view.xml',
                'view/voucher_view.xml',
                'view/invoice_view.xml',
                'view/advance_request_view.xml',
                'view/transaction_type_view.xml',
                'view/transaction_type_amo_rest_view.xml',
                'view/advance_return_view.xml',
                'view/expedient_category_view.xml',
                'view/location_view.xml',
                'view/budget_modification_detail_view.xml',
                'view/funding_move_view.xml',
                'view/invoice_line_view.xml',
                'view/rest_type_view.xml',
                'view/users_view.xml',
                'view/budget_position_view.xml',
                'view/company_view.xml',
                'view/budget_detail_view.xml',
                'view/budget_prec_detail_view.xml',
                'view/preventive_line_view.xml',
                'view/definitive_line_view.xml',
                'view/account_view.xml',
                'view/transaction_view.xml',
                'view/budget_position_category_view.xml',
                'view/budget_view.xml',
                'view/remit_view.xml',
                'view/advance_return_line_view.xml',
                'view/budget_pos_exc_rest_view.xml',
                'view/budget_modification_view.xml',
                'view/expedient_view.xml',
                'view/advance_request_line_view.xml',
                'view/expedient_founder_view.xml',
                'view/res_partner_view.xml',
                'data/account_voucher_properties.xml',
                'data/inventory_rule_properties.xml',
                'data/voucher_properties.xml',
                'data/invoice_properties.xml',
                'data/advance_request_properties.xml',
                'data/transaction_type_properties.xml',
                'data/transaction_type_amo_rest_properties.xml',
                'data/advance_return_properties.xml',
                'data/expedient_category_properties.xml',
                'data/location_properties.xml',
                'data/budget_modification_detail_properties.xml',
                'data/funding_move_properties.xml',
                'data/invoice_line_properties.xml',
                'data/rest_type_properties.xml',
                'data/users_properties.xml',
                'data/budget_position_properties.xml',
                'data/company_properties.xml',
                'data/budget_detail_properties.xml',
                'data/budget_prec_detail_properties.xml',
                'data/preventive_line_properties.xml',
                'data/definitive_line_properties.xml',
                'data/account_properties.xml',
                'data/transaction_properties.xml',
                'data/budget_position_category_properties.xml',
                'data/budget_properties.xml',
                'data/remit_properties.xml',
                'data/advance_return_line_properties.xml',
                'data/budget_pos_exc_rest_properties.xml',
                'data/budget_modification_properties.xml',
                'data/expedient_properties.xml',
                'data/advance_request_line_properties.xml',
                'data/expedient_founder_properties.xml',
                'data/account_voucher_track.xml',
                'data/inventory_rule_track.xml',
                'data/voucher_track.xml',
                'data/invoice_track.xml',
                'data/advance_request_track.xml',
                'data/transaction_type_track.xml',
                'data/transaction_type_amo_rest_track.xml',
                'data/advance_return_track.xml',
                'data/expedient_category_track.xml',
                'data/location_track.xml',
                'data/budget_modification_detail_track.xml',
                'data/funding_move_track.xml',
                'data/invoice_line_track.xml',
                'data/rest_type_track.xml',
                'data/users_track.xml',
                'data/budget_position_track.xml',
                'data/company_track.xml',
                'data/budget_detail_track.xml',
                'data/budget_prec_detail_track.xml',
                'data/preventive_line_track.xml',
                'data/definitive_line_track.xml',
                'data/account_track.xml',
                'data/transaction_track.xml',
                'data/budget_position_category_track.xml',
                'data/budget_track.xml',
                'data/remit_track.xml',
                'data/advance_return_line_track.xml',
                'data/budget_pos_exc_rest_track.xml',
                'data/budget_modification_track.xml',
                'data/expedient_track.xml',
                'data/advance_request_line_track.xml',
                'data/expedient_founder_track.xml',
                'data/sequence.xml',
                'workflow/transaction_workflow.xml',
                'workflow/budget_workflow.xml',
                'workflow/expedient_workflow.xml',
                'workflow/funding_move_workflow.xml',
                'workflow/advance_request_workflow.xml',
                'workflow/advance_return_workflow.xml',
                'workflow/remit_workflow.xml',
                'security/ir.model.access.csv',
                'view/public_budget_menuitem.xml',
                'view/public_budget_actions.xml',
                'report/remit_report.xml',
             ],
    'depends': [
        'account',
        'report_aeroo',
        'account_invoice_auto_pay',
    ],
    'description': 'Public Budget',
    'installable': True,
    'license': 'AGPL-3',
    'name': 'Public Budget',
    'test': [],
    'version': 'No version',
    'website': ''}
# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
